### ISSUE TITLE
Data: Missing ICD-10 to WBD 10 codes

### ISSUE THREAD

**Issue by git-cheryl** [cghr-toronto/icd#10]
Some ICD codes were found in _Version 10 - Final CGHR-GBD list 18 April 2013 RW (original Wilson).xls_, but not found in [icd10towbd10.csv](https://github.com/cghr-toronto/icd/blob/main/data/icd10towbd10.csv).

For example, Child-G03 code is found in Wilson's, but only Neo-G03 and Adult-G03 were found in _icd10towbd10.csv_. Furthermore, there are 2 duplicates of Neo-G03. 
![image](https://user-images.githubusercontent.com/107133721/221891354-6f4062fa-5e57-4de6-a1a2-bbbcef1906fa.png)

The list of ICD codes missing from _icd10towbd10.csv_ are here:
[missing_icd_2023-02-28.csv](https://github.com/cghr-toronto/icd/files/10851624/missing_icd_2023-02-28.csv)

**Comment by git-cheryl** [comment]
[icd10towbd10.csv](https://github.com/cghr-toronto/icd/blob/main/data/icd10towbd10.csv) is from github, the Wilson's file I think I got it from you but forgot where

**Comment by git-cheryl** [comment]
@rrwen 
Most updated list by Wilson:
[Version 10 - Final CGHR-GBD list 18 April 2013_Updated 12Jan2023.xls](https://github.com/cghr-toronto/icd/files/10862275/Version.10.-.Final.CGHR-GBD.list.18.April.2013_Updated.12Jan2023.xls)

List of ICD missing from Richard's icd10towbd10.csv
[missing_icd_2023-02-28.csv](https://github.com/cghr-toronto/icd/files/10862277/missing_icd_2023-02-28.csv)

**Comment by rrwen** [comment]
Solved with commit 2f7d113

There was a bug with `rbind` and combining the age grouped WBD excel sheets into one before running the `expandICD10Data` function

The fix was to run `expandICD10Data` individually for each age grouped excel sheet, before combining them into a common table

The src/data/icd10towbd10.csv file should be consistent with Wilson’s Jan 2023 WBD codes
